---
title: "Data overview"
author: "Joyce Hsiao"
output: html_document
---

<!-- The file analysis/chunks.R contains chunks that define default settings
shared across the workflowr files. -->
```{r read-chunk, include=FALSE, cache=FALSE}
knitr::read_chunk("chunks.R")
```

<!-- Update knitr chunk options -->
```{r knitr-opts-chunk, include=FALSE}
```

<!-- Insert the date the file was last updated -->
```{r last-updated, echo=FALSE, results='asis'}
```

<!-- Insert the code version (Git commit SHA1) if Git repository exists and R
 package git2r is installed -->
```{r code-version, echo=FALSE, results='asis'}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---

Data processing steps are as follows:

1. [QIIME for read alignment](log_20171207080411.txt)

2. [Build MRexperiment object](step0_build_MRexperiment.html)

3. [Filtering samples and OTUs](step1_filtering.html)

4. [Normalization and Batch correction](step2_normalization_batch.html)

5. [Grades of membership model](step3_gradesOfMembership.html)


---

## Session information

```{r, echo = FALSE}
sessionInfo()
```

