---
title: "Differential abundance analysis"
author: "JNP"
output: html_document
---

<!-- The file analysis/chunks.R contains chunks that define default settings
shared across the workflowr files. -->
```{r read-chunk, include=FALSE, cache=FALSE}
knitr::read_chunk("chunks.R")
```

<!-- Update knitr chunk options -->
```{r knitr-opts-chunk, include=FALSE}
```

<!-- Insert the date the file was last updated -->
```{r last-updated, echo=FALSE, results='asis'}
```

<!-- Insert the code version (Git commit SHA1) if Git repository exists and R
 package git2r is installed -->
```{r code-version, echo=FALSE, results='asis'}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=F, message=F)
```

---


## Loading data and packages

```{r}
library(knitr)
library(kableExtra)
library(dplyr)
library(metagenomeSeq)
library(CountClust)
```

Read in filtered, corrected, etc data.

```{r}
load("../data/nasal_GOM.rdata")
MRobj
```

$~$

---

## Differential abundance analysis


```{r}
cl = pData(MRobj)$GOM
mod = model.matrix(~cl)
fit = fitFeatureModel(MRobj,mod)
MRfulltable(fit,number = nrow(MRobj),file="~/Desktop/tbl.tsv")
```


$~$


---

## Session Info

```{r, echo = F}
sessionInfo()
```
