---
title: "Home"
output:
  html_document:
    toc: false
---

Share results of nasal microbiome project.

* [Processing reads - from reads to count table](data-overview.html)

* Cluster analysis (Applying GoM - Grades of Membership model)
    * [Choosing number of clusters](chossing-number-of-clusters.html)
    * [GOM cluster memberships under different seeds](gom-seeds.html)
    * [Grades of membership model finalized](step3_gradesOfMembership.html)
    * [Variance explained under different k](cluster-variance-explained.html)
  
* Cluster characteristics
    * [Stacked bar plot of abundance](stacked_bar_plots.html)
    * [Diversity](cluster-diversity.Rmd)
    * [Explore sample cluster probabilities in relation to the PCA outliers](explore-cluster-probability-.html)
    
* Differential abudance analysis between two clusters
    * [At the species level](differential_abundance.html)
    * [At higher phylogenetic taxa level](differential_abundance_higher_order.html)

* [Applying GoM to HMP data](hmp.html)

---

* Shiny site for our exploratory data analysis
    http://138.197.10.90:3838/shiny/shinyapp/


